---
pid: /var/www/timejust/staging/timejust-api/current/tmp/pids/thin.pid
address: 127.0.0.1
timeout: 5
port: 7001
log: /var/www/timejust/staging/timejust-api/current/log/thin.log
max_conns: 1024
require: ['rubygems']

environment: staging
max_persistent_conns: 512
servers: 2
daemonize: true
chdir: /var/www/timejust/staging/timejust-api/current
