:all:
  :gadget:
    :js:
      :home_canvas:
        - vendor/assets/javascripts/jquery.js
        - vendor/assets/javascripts/underscore.js
        - vendor/assets/javascripts/backbone.min.js
        - vendor/assets/javascripts/jquery.dateFormat.js
        - app/assets/javascripts/lib/poll.js
        - app/assets/javascripts/lib/google_request.js
        - app/assets/javascripts/lib/string.js
        - app/assets/javascripts/gadget_common.js
        - app/assets/javascripts/models/user.js
        - app/assets/javascripts/models/event.js
        - app/assets/javascripts/models/travel.js
        - app/assets/javascripts/models/travel_step.js
        - app/assets/javascripts/controllers/gadget.js
      :home:
        - app/assets/javascripts/views/gadget/event.js
        - app/assets/javascripts/views/gadget/travels.js
        - app/assets/javascripts/views/gadget/travel.js
        - app/assets/javascripts/views/gadget/travel_step.js
      :canvas:
        - app/assets/javascripts/views/gadget/travel_nodes_selector.js
