:all:
  :shared_calendars:
    :bus:
      :name: 'GreenProposal'
      :color: '#0D7813'
      :color_id: '13'
    :train:
      :name: 'PinkProposal'
      :color: '#B1365F'
      :color_id: '22'
    :car:
      :name: 'YellowProposal'
      :color: '#AB8B00'
      :color_id: '11'
      
:development:
  :gapps:
    :oauth:
      :for_domains:
        # :consumer_key: '42901100597.apps.googleusercontent.com'
        # :consumer_secret: '4vY64qUlVQDdd3uYbH0k9hmD'
        :consumer_key: '492334720932.apps.googleusercontent.com'
        :consumer_secret: 'JgfEGLXljg6zQfrOL--h2MKw'
      :for_gmail:
        # :consumer_key: '42901100597.apps.googleusercontent.com'
        # :consumer_secret: '4vY64qUlVQDdd3uYbH0k9hmD'
        :consumer_key: '492334720932.apps.googleusercontent.com'
        :consumer_secret: 'JgfEGLXljg6zQfrOL--h2MKw'        
        
:staging:
  :gapps:
    :oauth:
      :for_domains:
        :consumer_key: '492334720932.apps.googleusercontent.com'
        :consumer_secret: 'JgfEGLXljg6zQfrOL--h2MKw'
      :for_gmail:
        :consumer_key: '492334720932.apps.googleusercontent.com'
        :consumer_secret: 'JgfEGLXljg6zQfrOL--h2MKw'
        
:production:
  :gapps:
    :oauth:
      :for_domains:
        :consumer_key: '748887703566.apps.googleusercontent.com'
        :consumer_secret: 'A7cJOR9YX15qygzeJULIcokb'
      :for_gmail:
        :consumer_key: '748887703566.apps.googleusercontent.com'
        :consumer_secret: 'A7cJOR9YX15qygzeJULIcokb'
