:all:
  :shared_calendars:
    :public_transport_faster:
      :name: 'GreenProposal'
      :color: '#0D7813'
    :public_transport_minimum_change:
      :name: 'PinkProposal'
      :color: '#B1365F'
    :car:
      :name: 'YellowProposal'
      :color: '#AB8B00'
  :gapps:
    :oauth:
      :for_domains:
        :consumer_key: '502137022926.apps.googleusercontent.com'
        :consumer_secret: 'RFvbtQoJM4wmxftpy17o1OJk'
      :for_gmail:
        :consumer_key: '54779436562.apps.googleusercontent.com'
        :consumer_secret: '0DoZNgo2ZJx3mT0D-QxdhJPF'
:test:
  :gapps:
    :oauth:
      :for_domains:
        :consumer_key: 'test_comsumer_key.apps.googleusercontent.com'
        :consumer_secret: 'test_consumer_secret'
      :for_gmail:
        :consumer_key: 'test_consumer_key.apps.googleusercontent.com'
        :consumer_secret: 'test_consumer_secret'
:dev:
  :gapps:
    :oauth:
      :for_gmail:
        :consumer_key: '22942625083.apps.googleusercontent.com'
        :consumer_secret: 'Fzt7HYOUpq-X187p0rkfB6Hq'
:staging:
  :gapps:
    :oauth:
      :for_gmail:
        :consumer_key: '723050567289.apps.googleusercontent.com'
        :consumer_secret: 'jnE2VYzhwcfUsy9BC29TL9t6'
