:development:
  :redis:
    :server:
      :host: localhost
      :port: 6379
      :namespace: timejust:development
    :services:
      :resque:
        :namespace: resque
        
:staging:
  :redis:
    :server:
      :host: localhost
      :port: 6379
      :namespace: timejust:staging
    :services:
      :resque:
        :namespace: resque
        
:production:
  :redis:
    :server:
      :host: localhost
      :port: 6379
      :namespace: timejust:production
    :services:
      :resque:
        :namespace: resque



