:all:
  :api:
    :url: "http://api.timejust.local/v1"
    :basic_auth:
      :user: "timejust"
      :password: "t1m3ju$t"
  :gadget:
    :url: "http://timejust-dev.af83.com/gadget/timejust.xml"
  :web:
    :url: "http://timejust-dev.af83.com"
:dev:
  :api:
    :url: "http://api.timejust-dev.af83.com/v1"
    :basic_auth:
      :user: "timejust"
      :password: "t1m3ju$t"
  :gadget:
    :url: "http://timejust-dev.af83.com/gadget/timejust.xml"
  :web:
    :url: "http://timejust-dev.af83.com"
  :ratp_proxy:
    :url: "http://proxy.bearstech.lan:8080/"
:staging:
  :api:
    :url: "http://api.timejust-staging.af83.com/v1"
    :basic_auth:
      :user: "timejust"
      :password: "t1m3ju$t"
  :gadget:
    :url: "http://timejust-staging.af83.com/gadget/timejust.xml"
  :web:
    :url: "http://timejust-staging.af83.com"
  :ratp_proxy:
    :url: "http://proxy.bearstech.lan:8080/"
