:development:
  :api:
    :url: "http://api.timejust.com:50001/v1"
    :basic_auth:
      :user: "timejust"
      :password: "t1m3ju$t" 
  :gadget:
    :url: "http://staging.timejust.com:50001/gadget/timejust.xml"
  :web:
    :url: "http://staging.timejust.com:50001"
  :ratp_proxy:
    :url: "http://proxy.timejust.com"
