:development:
  :api:
    :url: "http://api.timejust.com:50001/v1"
    :basic_auth:
      :user: "timejust"
      :password: "t1m3ju$t" 
  :gadget:
    :url: "http://staging.timejust.com:50001/gadget/timejust.xml"
  :web:
    :url: "http://staging.timejust.com:50001"
  :ratp_proxy:
    :url: "http://proxy.timejust.com:80"
  :service:
    :url: "http://service-staging.timejust.com"
    :geo_recognition: "v1/geo/recognition"
    :geo_direction: "v1/geo/direction"
:staging:
  :api:
    :url: "http://api-staging.timejust.com/v1"
    :basic_auth:
      :user: "timejust"
      :password: "t1m3ju$t" 
  :gadget:
    :url: "http://staging.timejust.com/gadget/timejust.xml"
  :web:
    :url: "http://staging.timejust.com"
  :ratp_proxy:
    :url: "http://proxy.timejust.com:80"
  :service:
    :url: "http://service-staging.timejust.com"
    :geo_recognition: "v1/geo/recognition"
    :geo_direction: "v1/geo/direction"
:production:
  :api:
    :url: "http://api.timejust.com/v1"
    :basic_auth:
      :user: "timejust"
      :password: "t1m3ju$t" 
  :gadget:
    :url: "http://beta.timejust.com/gadget/timejust.xml"
  :web:
    :url: "http://beta.timejust.com"
  :ratp_proxy:
    :url: "http://proxy.timejust.com:80"
  :service:
    :url: "http://service.timejust.com"
    :geo_recognition: "v1/geo/recognition"
    :geo_direction: "v1/geo/direction"
